In [28]:
import pandas as pd

data= pd.read_excel('./발주자_공종별_건설수주액_경상.xlsx')

data

c:\Users\LWG\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,발주자별,공종별,1978.01,1978.02,1978.03,1978.04,1978.05,1978.06,1978.07,1978.08,...,2023.03,2023.04,2023.05,2023.06,2023.07,2023.08,2023.09,2023.10,2023.11 p),2023.12 p)
0,수주총액,계,42996,48172,95751,105701,236202,137230,135029,181838,...,11389994,9625644,15459819,17675270,9439602,8348246,14059045,14251062,12545547,31647560
1,NaN,건축,33016,22929,63790,58611,166849,99465,65657,129317,...,9227730,7142271,9341892,11819719,6856422,6587115,9869605,11511274,9820743,14651358
2,NaN,토목,9980,25243,31961,47090,69353,37765,69372,52521,...,2162264,2483373,6117927,5855551,2583180,1761131,4189440,2739788,2724804,16996202
3,공공부문,계,6689,26072,34137,61145,102845,65191,84882,63800,...,1716583,2344713,3205949,4240785,2149620,1916847,1250099,2194496,3155596,18365850
4,NaN,건축,804,1427,7456,18322,35819,33177,20426,18300,...,464600,938721,655116,864995,443963,1078552,413296,1154077,1585976,3297493
5,NaN,토목,5885,24645,26681,42823,67026,32014,64456,45500,...,1251983,1405992,2550833,3375790,1705657,838295,836803,1040419,1569620,15068357
6,민간부문,계,36294,22072,61605,44529,132671,70812,49971,115809,...,9303663,7051662,11093807,12196128,7245629,6386840,11074843,11796801,9180812,12922521
7,NaN,건축,32199,21502,56325,40262,130344,65061,45156,109419,...,8702666,6182083,8529720,10916952,6385611,5501316,9438238,10333683,8189763,11014723
8,NaN,토목,4095,570,5280,4267,2327,5751,4815,6390,...,600997,869579,2564087,1279176,860018,885524,1636605,1463118,991049,1907798
9,국내외국기관,계,13,28,9,27,686,1227,176,2229,...,3038,1782,10020,20778,5598,9897,22736,1961,7649,323842
10,NaN,건축,13,0,9,27,686,1227,75,1598,...,3038,1043,7807,17060,5132,6789,15267,1750,4898,323842
11,NaN,토목,0,28,0,0,0,0,101,631,...,0,739,2213,3718,466,3108,7469,211,2751,0
12,민자,계,-,-,-,-,-,-,-,-,...,366710,227487,1150043,1217579,38755,34662,1711367,257804,201490,35347
13,NaN,건축,-,-,-,-,-,-,-,-,...,57426,20424,149249,20712,21716,458,2804,21764,40106,15300
14,NaN,토목,-,-,-,-,-,-,-,-,...,309284,207063,1000794,1196867,17039,34204,1708563,236040,161384,20047